import './global.css';
import Link from "next/link";

export const metadata = {
  title: 'Welcome to inventory',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav className="bg-gray-800 text-white p-4">
          <ul className="flex space-x-4">
            <li>
              <Link href="/" className="hover:text-gray-300">
                Home
              </Link>
            </li>
            <li>
              <Link href="/products" className="hover:text-gray-300">
                Products
              </Link>
            </li>
            <li>
              <Link href="/sellers" className="hover:text-gray-300">
                Sellers
              </Link>
            </li>
          </ul>
        </nav>
        <main className="p-4">{children}</main>
      </body>
    </html>
  );
}
